# Generated by Django 5.0.3 on 2024-04-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_tercera', '0002_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='camada',
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
