# Generated by Django 5.0.3 on 2024-04-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_tercera', '0006_alumno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='nombre',
            new_name='Nombre_y_Apellido',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='materia',
            new_name='Materia',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='nombre',
            new_name='Nombre_y_Apellido',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='apellido',
        ),
        migrations.AddField(
            model_name='alumno',
            name='Asignatura',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
